steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-web-app', '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/node-web-app']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit-faisal-alam-dc41412/node-web-app:latest']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

  




